logging:
  pattern:
    level: '%5p [${spring.properties.name:},%X{traceId:-},%X{spanId:-}]'
server:
  port: 8083
  servlet:
    context-path: ${CONTEXT_PATH:/api/v1}
spring:
  application:
    name: user-server
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 50
        one-indexed-parameters: false
        page-parameter: page
        size-parameter: size
      sort:
        sort-parameter: sort
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    password: ${SPRING_DATASOURCE_PASSWORD}
    url: jdbc:mysql://localhost:3306/pattern_dao?createDatabaseIfNotExist=true&useTimezone=true&serverTimezone=UTC
    username: root
  jackson:
    #default-property-inclusion: non_null
    serialization:
      fail_on_empty_beans: false
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    show-sql: ${JPA_SHOW_SQL:false}